# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-RbbYa7bRaewW6TMZS_-VCd0mUP--iy
"""

import streamlit as st
import numpy as np
import joblib

# Load model and label encoder
model = joblib.load("crop_recommender_model.pkl")
le = joblib.load("label_encoder.pkl")

st.title("🌱 Crop Recommendation System")
st.markdown("Enter soil and weather data to get a crop recommendation")

# Input form
N = st.number_input("Nitrogen (N)", min_value=0, max_value=150, value=50)
P = st.number_input("Phosphorus (P)", min_value=0, max_value=150, value=50)
K = st.number_input("Potassium (K)", min_value=0, max_value=150, value=50)
temperature = st.number_input("Temperature (°C)", min_value=0.0, max_value=50.0, value=25.0)
humidity = st.number_input("Humidity (%)", min_value=0.0, max_value=100.0, value=60.0)
ph = st.number_input("pH", min_value=0.0, max_value=14.0, value=6.5)
rainfall = st.number_input("Rainfall (mm)", min_value=0.0, max_value=300.0, value=100.0)

# Predict button
if st.button("Predict Crop"):
    input_data = np.array([[N, P, K, temperature, humidity, ph, rainfall]])
    prediction = model.predict(input_data)
    crop = le.inverse_transform(prediction)[0]
    st.success(f"🌾 Recommended Crop: **{crop}**")